version: "3"

services:
  keycloak:
    build: keycloak/
    container_name: keycloak
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/data:/opt/keycloak/data
    command:
      - start-dev
  
  influxdb:
    build: influx/
    container_name: influx
    volumes:
      - ./influx/data:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
    ports:
      - 8086:8086
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=password
    - DOCKER_INFLUXDB_INIT_ORG=organization
    - DOCKER_INFLUXDB_INIT_BUCKET=bucket