version: "3"

services:
  keycloak:
    build: keycloak/
    container_name: keycloak
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/data:/opt/keycloak/data
    command:
      - start-dev
    networks:
      - gantry-dev-networks
  
  webhook-service:
    build: cmd/webhook-service/
    container_name: webhook-service
    tty: true
    stdin_open: true
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - HOST=0.0.0.0
    networks:
      - gantry-dev-networks
    depends_on:
      - keycloak

networks:
  gantry-dev-networks:
    external:
      true