apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gantry-bff
  labels:
    app:  gantry-bff
spec:
  selector:
    matchLabels:
      app: gantry-bff
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  gantry-bff
    spec:
      containers:
      - name:  gantry-bff
      # TODO:gantryCDのwebuiイメージを指定
        image:  MYAPP:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: gantry-configs
              key: TZ


        ports:
        - containerPort:  8080
          name:  gantry-bff
      restartPolicy: Always